apiVersion: v1

kind: Service

metadata:
  name: bankingapp-customerapi-service

spec:
  type: LoadBalancer

  selector:
    app: bankingapp-customerapi

  ports:
    - port: 80
      targetPort: 8080